apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-automated
  namespace: argo
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d21b1adce3eb6b02.efs.us-east-1.amazonaws.com
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-automated
  volumeMode: Filesystem
