apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-automated
  namespace: argo
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: EFS_DNS
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-automated
  volumeMode: Filesystem
