apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-automated
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc-automated

